disqus_shortname: yoomeedev
site_url: http://localhost:3000
facebook_app_id: '137557166307145'
xero:
  consumer_key: 0SNJMCJGMIVJRBSXVBNOCGTTCODN7K
  consumer_secret: QQXKL40CUOOPRXB9I6U2IR1PEP8TT7
  privatekey_path: lib/xero/development/privatekey.pem