disqus_shortname: yoomeedev
site_url: http://localhost:3000
facebook_app_id: '137557166307145'
xero:
  consumer_key: 6XTOPBWLR0BWAFWILOG6JLSMKB3PTZ
  consumer_secret: TG3RUFELS1JG7HTH6ENEROV8GBN2GL
  privatekey_path: lib/xero/development/privatekey.pem