disqus_shortname: thenutribox
site_url: https://thenutribox.com
facebook_app_id: '443658312367297'
xero:
  consumer_key: PZCLDI8SHUWKXEVHMOXR7WUVAI3ESG
  consumer_secret: KHQXL1UOGNDSDCUF8DEVYEGZC481EA
  privatekey_path: lib/xero/production/privatekey.pem
